'use strict';
const http=require('node:http');
const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const {WebSocketServer,WebSocket}=require('ws');
const PORT=Number(process.env.PORT)||8787;
const DATA_DIR=process.env.DATA_DIR||path.join(__dirname,'data');
const DATA_FILE=path.join(DATA_DIR,'accounts.json');
const MAX_ROOM_PLAYERS=8,MAX_WALLS=16;
fs.mkdirSync(DATA_DIR,{recursive:true});
let accounts={};
try{accounts=JSON.parse(fs.readFileSync(DATA_FILE,'utf8'))||{}}catch(_){accounts={}}
function persist(){const temp=DATA_FILE+'.tmp';fs.writeFileSync(temp,JSON.stringify(accounts,null,2));fs.renameSync(temp,DATA_FILE)}
const GAME_FILE=path.join(__dirname,'index.html');
const httpServer=http.createServer((req,res)=>{const pathname=new URL(req.url||'/', 'http://localhost').pathname;if(pathname==='/health'){res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify({ok:true,rooms:rooms.size,online:sockets.size}))}if(pathname==='/'||pathname==='/index.html'){if(!fs.existsSync(GAME_FILE)){res.writeHead(503,{'content-type':'text/plain; charset=utf-8'});return res.end('Jogo ainda não foi publicado.')}res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-cache'});return fs.createReadStream(GAME_FILE).pipe(res)}res.writeHead(404,{'content-type':'text/plain; charset=utf-8'});res.end('Not found')});
const wss=new WebSocketServer({server:httpServer,path:'/ws',maxPayload:8192});
const sockets=new Map();
const rooms=new Map();
function send(ws,data){if(ws&&ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify(data))}
function sendUser(username,data){send(sockets.get(username),data)}
function cleanName(value){return String(value||'').trim().replace(/^@/,'').toLowerCase()}
function validName(name){return /^[a-z0-9_]{3,16}$/.test(name)}
function tokenHash(token){return crypto.createHash('sha256').update(String(token||'')).digest('hex')}
function publicProfile(name){const u=accounts[name];return{username:name,friends:u.friends||[],requests:u.requests||[],invites:(u.invites||[]).filter(x=>rooms.has(x.room))}}
function pushProfile(name){sendUser(name,{type:'profile',profile:publicProfile(name)})}
function tellRoom(room,data,except=null){for(const [name,p] of room.players){if(name!==except)send(sockets.get(name),data)}}
function newRoomCode(){let code;do{code=crypto.randomBytes(3).toString('hex').toUpperCase()}while(rooms.has(code));return code}
function freshWalls(){return[{id:'base-a',x:-6,z:-3,rotation:0,owner:'map'},{id:'base-b',x:6,z:-3,rotation:0,owner:'map'},{id:'base-c',x:0,z:-11,rotation:Math.PI/2,owner:'map'},{id:'base-d',x:-10,z:-18,rotation:0,owner:'map'},{id:'base-e',x:10,z:-18,rotation:0,owner:'map'}]}
function makeRoom(){const code=newRoomCode();const room={code,players:new Map(),walls:freshWalls(),createdAt:Date.now()};rooms.set(code,room);return room}
function leaveRoom(ws){if(!ws.room||!ws.user)return;const room=ws.room,name=ws.user;room.players.delete(name);ws.room=null;tellRoom(room,{type:'playerLeft',username:name});if(!room.players.size)rooms.delete(room.code)}
function joinRoom(ws,code){if(!ws.user)return send(ws,{type:'error',message:'Entre com um nome antes de entrar na sala.'});let room=rooms.get(String(code||'').toUpperCase());if(!room)return send(ws,{type:'error',message:'Sala não encontrada; peça um novo convite.'});if(room.players.size>=MAX_ROOM_PLAYERS&&!room.players.has(ws.user))return send(ws,{type:'error',message:'Sala cheia.'});leaveRoom(ws);const others=[...room.players.values()];const initial={id:ws.user,username:ws.user,x:0,y:0,z:9,yaw:0,hp:100,weapon:'m4'};room.players.set(ws.user,initial);ws.room=room;send(ws,{type:'roomJoined',room:room.code,self:initial,players:others,walls:room.walls});tellRoom(room,{type:'playerJoined',player:initial},ws.user)}
function fail(ws,message){send(ws,{type:'error',message})}
function auth(ws,msg){const name=cleanName(msg.username),token=String(msg.token||'');if(!validName(name))return fail(ws,'Use um nome com 3–16 letras, números ou _.');if(token.length<32)return fail(ws,'Não consegui validar o dispositivo; tente novamente.');const hash=tokenHash(token);let u=accounts[name];if(u){if(u.tokenHash!==hash)return fail(ws,'Este nome já está registrado neste servidor. Use o dispositivo original.')}else{u=accounts[name]={tokenHash:hash,friends:[],requests:[],invites:[],createdAt:Date.now()};persist()}const previous=sockets.get(name);if(previous&&previous!==ws){send(previous,{type:'error',message:'Sua conta foi conectada em outro aparelho.'});previous.close()}ws.user=name;sockets.set(name,ws);send(ws,{type:'authOk',profile:publicProfile(name)});for(const friend of u.friends||[])if(sockets.has(friend)){send(ws,{type:'presence',username:friend,online:true});sendUser(friend,{type:'presence',username:name,online:true})}for(const invite of u.invites||[])if(rooms.has(invite.room))send(ws,{type:'inviteReceived',invite})}
function handle(ws,msg){if(!msg||typeof msg.type!=='string')return;if(msg.type==='auth')return auth(ws,msg);if(!ws.user)return fail(ws,'Primeiro entre com seu nome de usuário.');const name=ws.user;
 if(msg.type==='createRoom'){leaveRoom(ws);const room=makeRoom();joinRoom(ws,room.code);return}
 if(msg.type==='joinRoom')return joinRoom(ws,msg.room);
 if(msg.type==='leaveRoom'){leaveRoom(ws);return send(ws,{type:'roomLeft'})}
 if(msg.type==='friendRequest'){const target=cleanName(msg.username);if(!validName(target))return fail(ws,'O nome precisa ter de 3 a 16 caracteres.');if(target===name)return fail(ws,'Não dá para adicionar a si mesmo.');const dest=accounts[target];if(!dest)return fail(ws,'Esse nome ainda não tem perfil no servidor.');if((accounts[name].friends||[]).includes(target))return fail(ws,'Essa pessoa já está na sua lista.');if(!(dest.requests||[]).includes(name)){dest.requests.push(name);persist();sendUser(target,{type:'friendRequestReceived',username:name});pushProfile(target)}return send(ws,{type:'notice',message:'Pedido de amizade enviado.'})}
 if(msg.type==='friendRespond'){const from=cleanName(msg.username),u=accounts[name],other=accounts[from];if(!u||!other||!(u.requests||[]).includes(from))return fail(ws,'Esse pedido não está mais disponível.');u.requests=u.requests.filter(x=>x!==from);if(msg.accept){if(!u.friends.includes(from))u.friends.push(from);if(!other.friends.includes(name))other.friends.push(name)}persist();pushProfile(name);pushProfile(from);if(msg.accept)sendUser(from,{type:'notice',message:name+' aceitou seu pedido de amizade.'});else sendUser(from,{type:'notice',message:name+' recusou seu pedido de amizade.'});return}
 if(msg.type==='inviteFriend'){const target=cleanName(msg.username),room=ws.room;if(!room)return fail(ws,'Entre em uma sala online antes de convidar.');if(!accounts[name].friends.includes(target))return fail(ws,'Só dá para convidar amigos aceitos.');const dest=accounts[target];if(!dest)return fail(ws,'Perfil de amigo não encontrado.');const invite={from:name,room:room.code,at:Date.now()};dest.invites=(dest.invites||[]).filter(x=>x.room!==room.code);dest.invites.push(invite);persist();sendUser(target,{type:'inviteReceived',invite});pushProfile(target);return send(ws,{type:'notice',message:'Convite enviado para '+target+'.'})}
 if(msg.type==='respondInvite'){const roomCode=String(msg.room||'').toUpperCase(),u=accounts[name];u.invites=(u.invites||[]).filter(x=>x.room!==roomCode);persist();pushProfile(name);if(msg.accept)return joinRoom(ws,roomCode);return send(ws,{type:'notice',message:'Convite recusado.'})}
 if(msg.type==='state'){const room=ws.room;if(!room)return;const old=room.players.get(name);if(!old)return;const now=Date.now();if(ws.lastStateAt&&now-ws.lastStateAt<55)return;ws.lastStateAt=now;const n=v=>Number.isFinite(Number(v))?Number(v):0;const state={...old,x:Math.max(-17,Math.min(17,n(msg.x))),y:Math.max(0,Math.min(5,n(msg.y))),z:Math.max(-41,Math.min(12,n(msg.z))),yaw:n(msg.yaw),weapon:msg.weapon==='carbine'?'carbine':'m4',hp:old.hp};room.players.set(name,state);tellRoom(room,{type:'playerState',player:state},name);return}
 if(msg.type==='hit'){const room=ws.room,targetName=cleanName(msg.target);if(!room||targetName===name)return;const shooter=room.players.get(name),target=room.players.get(targetName);if(!shooter||!target||target.hp<=0)return;const now=Date.now();if(ws.lastHitAt&&now-ws.lastHitAt<120)return;ws.lastHitAt=now;const d=Math.hypot(shooter.x-target.x,shooter.z-target.z);if(d>60)return;const base=msg.weapon==='carbine'?18:16,damage=base*(msg.zone==='head'?2:1);target.hp=Math.max(0,target.hp-damage);room.players.set(targetName,target);tellRoom(room,{type:'healthUpdate',username:targetName,hp:target.hp,by:name});if(target.hp===0){setTimeout(()=>{const current=rooms.get(room.code);if(!current||!current.players.has(targetName))return;const p=current.players.get(targetName);p.hp=100;const spots=[[0,9],[4,9],[-4,9],[0,0],[0,11],[-4,0],[4,0],[0,-4]],i=[...current.players.keys()].indexOf(targetName),spot=spots[i%spots.length];p.x=spot[0];p.z=spot[1];current.players.set(targetName,p);tellRoom(current,{type:'playerRespawn',player:p})},2200)}return}
 if(msg.type==='placeWall'){const room=ws.room;if(!room)return fail(ws,'Você não está em uma sala.');const own=room.walls.filter(w=>w.owner===name);if(room.walls.length>=MAX_WALLS||own.length>=3)return fail(ws,'Limite de paredes da sala atingido.');const x=Number(msg.x),z=Number(msg.z),rotation=Math.abs(Number(msg.rotation))>0.7?Math.PI/2:0;if(!Number.isFinite(x)||!Number.isFinite(z)||Math.abs(x)>15||z< -39||z>10)return fail(ws,'Posição inválida para construir.');const wall={id:crypto.randomUUID(),x,z,rotation,owner:name};room.walls.push(wall);tellRoom(room,{type:'wallAdded',wall});return}
}
wss.on('connection',ws=>{ws.on('message',raw=>{try{handle(ws,JSON.parse(raw.toString()))}catch(e){fail(ws,'Mensagem inválida.')}});ws.on('close',()=>{if(ws.user&&sockets.get(ws.user)===ws){sockets.delete(ws.user);for(const friend of accounts[ws.user]?.friends||[])sendUser(friend,{type:'presence',username:ws.user,online:false})}leaveRoom(ws)});ws.on('error',()=>{})});
setInterval(()=>{for(const ws of wss.clients)if(ws.readyState===WebSocket.OPEN)ws.ping()},25000);
httpServer.listen(PORT,'0.0.0.0',()=>console.log('Treino City online server listening on '+PORT));
